baseURL = "https://www.grid47.xyz/"
languageCode = "en-us"
title = "grid47"
theme = "local-theme"
copyright = "www.grid47.com - All rights reserved"
enableEmoji = true
publishDir = "public"
disqusShortname = "grid47"
googleAnalytics = "G-1LN7R4LHR1"
#summaryLength=1

title: "My Page"
[sitemap]
  changefreq: "monthly"
  priority: 0.7

[params]
  logo = "/images/logo.png"
  description ="Blog by grid47"
  #mailchimp = "you can provide a mailchimp-link here"
  customcss = ["/css/leetcode.css"]  

[params.author]
  name = "grid47"
  thumbnail = "/images/logo.png"
  description = "Exploring patterns and algorithms"

[params.index]
  picture = "/images/avatar.jpeg"
  title = "Mohammed Yasir Eramangadan"
  subtitle = "Engineer & Programmer"
  mdtext = '''
Hey there! Thanks for stopping by. Check out my Algorithms course in the course section to get started! 🚀
'''
  alertbar = false

[params.social]
  github = "grid47"
  linkedin = "grid47"
  udemy = "grid47"
  youtube = "grid47"
  leetcode = "grid47"

## Main Menu
[[menu.main]]
  name = "About"
  identifier = "about"
  weight = 1
  url = "/about/"

[[menu.main]]
  name = "LeetCode"
  identifier = "leetcode"
  weight = 2
  url = "/leetcode/"

[[menu.main]]
  name = "Course"
  identifier = "course"
  weight = 3
  url = "/courses/"

[[menu.main]]
  name = "Terms & Policy"
  identifier = "terms"  
  weight = 4
  url = "/terms/"

[[menu.main]]
  name = "Contact"
  identifier = "contact"  
  weight = 5
  url = "/contact/"
    
[markup.highlight]
    noClasses = true
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noHl = false
    style = 'emacs'
    tabWidth = 4

[params.copyTexts]
coupen = "ALGORITHMS"

[build]
layoutsDir = "layouts"

[permalinks]
lists = "/lists/:slug/"

#[module]
#[[module.imports]]
#  path = 'github.com/lgaida/mediumish-gohugo-theme'